"""Crystal Engine - Block-to-Python compiler."""
from editor.block_definitions import get_block, generate_block_code


RUNTIME_HEADER = \'\'\'#!/usr/bin/env python3
# Generated by Crystal Engine
import pygame, sys, os, math, random, time, threading
pygame.init()
pygame.mixer.init()
\'\'\'


class Compiler:
    def __init__(self, project: dict):
        self._project = project

    def compile(self) -> str:
        p = self._project
        parts = [RUNTIME_HEADER]
        parts.append(self._emit_constants())
        parts.append(self._emit_asset_loader())
        parts.append(self._emit_sprite_class())
        parts.append(self._emit_game_class())
        parts.append(self._emit_screen_classes())
        parts.append(self._emit_main())
        return "\\n".join(parts)

    # ── Constants ─────────────────────────────────────────────────────────

    def _emit_constants(self):
        p = self._project
        return (
            f"WINDOW_TITLE = {p.get('window_title','Crystal Game')!r}\\n"
            f"WINDOW_W     = {p.get('width', 1280)}\\n"
            f"WINDOW_H     = {p.get('height', 720)}\\n"
            f"FPS          = {p.get('fps', 60)}\\n"
        )

    # ── Asset loader ──────────────────────────────────────────────────────

    def _emit_asset_loader(self):
        assets = self._project.get("assets", {})
        lines = [
            "# ── Embedded assets ─────────────────────────────────────",
            "import base64, io",
            "_ASSETS = {}",
        ]
        for name, b64 in assets.items():
            lines.append(f"_ASSETS[{name!r}] = base64.b64decode({b64!r})")
        lines += [
            "",
            "def _load_surface(name):",
            "    data = _ASSETS.get(name)",
            "    if not data: return None",
            "    try: return pygame.image.load(io.BytesIO(data)).convert_alpha()",
            "    except: return None",
            "",
        ]
        return "\\n".join(lines)

    # ── CrystalSprite ─────────────────────────────────────────────────────

    def _emit_sprite_class(self):
        return \'\'\'
# ── CrystalSprite ─────────────────────────────────────────────────────────────

class CrystalSprite:
    def __init__(self, name, asset_key="", x=0.5, y=0.5,
                 scale=1.0, visible=True, animations=None, zorder=0):
        self.name       = name
        self.asset_key  = asset_key
        self.px         = float(x)
        self.py         = float(y)
        self.scale      = float(scale)
        self.visible    = visible
        self.animations = animations or {}
        self.zorder     = int(zorder)
        self.angle      = 0.0
        self.opacity    = 255
        self.tint       = None
        self.vx         = 0.0
        self.vy         = 0.0
        self._surface   = None
        self._say_text  = None
        self._say_until = 0.0
        self._anim_name = None
        self._anim_idx  = 0
        self._anim_t    = 0.0
        self._clones    = []

    def _base_surf(self):
        if self._surface is None and self.asset_key:
            self._surface = _load_surface(self.asset_key)
        return self._surface

    def _cur_surf(self):
        if self._anim_name and self._anim_name in self.animations:
            frames = self.animations[self._anim_name].get("frames", [])
            if frames:
                s = _load_surface(f"sprites/{frames[self._anim_idx % len(frames)]}")
                if s: return s
        return self._base_surf()

    def render(self, surface, sw, sh):
        if not self.visible: return
        src = self._cur_surf()
        if src is None:
            px, py = int(self.px*sw), int(self.py*sh)
            sz = max(4, int(min(sw,sh)*0.04*self.scale))
            pygame.draw.rect(surface,(74,144,217),(px-sz,py-sz,sz*2,sz*2))
            return
        base = max(1, int(min(sw,sh)*0.08*self.scale))
        img  = pygame.transform.scale(src, (base, base))
        if self.angle:
            img = pygame.transform.rotate(img, -self.angle)
        if self.opacity < 255:
            img = img.copy(); img.set_alpha(self.opacity)
        if self.tint:
            t = img.copy()
            t.fill(self.tint+(0,), special_flags=pygame.BLEND_RGBA_MULT)
            img = t
        px = int(self.px*sw) - img.get_width()//2
        py = int(self.py*sh) - img.get_height()//2
        surface.blit(img, (px, py))
        if self._say_text and time.time() < self._say_until:
            fnt = pygame.font.SysFont("Segoe UI", 16)
            ts  = fnt.render(str(self._say_text), True, (255,255,255))
            bx, by = px, py - ts.get_height() - 6
            pygame.draw.rect(surface,(30,30,30),(bx-4,by-4,ts.get_width()+8,ts.get_height()+8),border_radius=6)
            surface.blit(ts, (bx, by))
        for cl in self._clones:
            cl.render(surface, sw, sh)

    def update_animation(self, dt):
        if not self._anim_name or self._anim_name not in self.animations: return
        fps = self.animations[self._anim_name].get("fps", 12)
        self._anim_t += dt
        if self._anim_t >= 1.0/max(1,fps):
            self._anim_t = 0
            frames = self.animations[self._anim_name].get("frames", [])
            if frames: self._anim_idx = (self._anim_idx+1) % len(frames)

    def rect(self, sw, sh):
        base = max(1, int(min(sw,sh)*0.08*self.scale))
        return pygame.Rect(int(self.px*sw)-base//2, int(self.py*sh)-base//2, base, base)

    # ── Motion API ────────────────────────────────────────────────────────
    def move(self, steps):
        rad = math.radians(self.angle)
        self.px = max(0.0,min(1.0,self.px+math.cos(rad)*float(steps)*0.001))
        self.py = max(0.0,min(1.0,self.py+math.sin(rad)*float(steps)*0.001))
    def set_x(self, x):       self.px = float(x)
    def set_y(self, y):       self.py = float(y)
    def change_x(self, dx):   self.px = max(0.0,min(1.0,self.px+float(dx)))
    def change_y(self, dy):   self.py = max(0.0,min(1.0,self.py+float(dy)))
    def goto(self, x, y):     self.px, self.py = float(x), float(y)
    def rotate(self, d):      self.angle = (self.angle+float(d)) % 360
    def set_angle(self, a):   self.angle = float(a) % 360
    def goto_sprite(self, name):
        t = _find_sprite(name)
        if t: self.px, self.py = t.px, t.py
    def bounce_on_edge(self):
        if self.px<=0 or self.px>=1: self.vx=-self.vx
        if self.py<=0 or self.py>=1: self.vy=-self.vy
    def set_velocity(self, vx, vy): self.vx, self.vy = float(vx), float(vy)
    def apply_velocity(self):
        self.px = max(0.0,min(1.0,self.px+self.vx*0.001))
        self.py = max(0.0,min(1.0,self.py+self.vy*0.001))
    # ── Appearance API ────────────────────────────────────────────────────
    def show(self):           self.visible = True
    def hide(self):           self.visible = False
    def set_scale(self, s):   self.scale   = max(0.01,float(s))
    def change_scale(self,d): self.scale   = max(0.01,self.scale+float(d))
    def set_opacity(self,a):  self.opacity = int(max(0,min(100,float(a)))*2.55)
    def set_layer(self,z):    self.zorder  = int(z)
    def set_tint(self, h):
        try: self.tint = tuple(int(h.lstrip("#")[i:i+2],16) for i in (0,2,4))
        except: self.tint = None
    def clear_tint(self): self.tint = None
    def play_animation(self, name):
        if name != self._anim_name:
            self._anim_name, self._anim_idx, self._anim_t = name, 0, 0
    def stop_animation(self):  self._anim_name = None
    def next_frame(self):
        if self._anim_name and self._anim_name in self.animations:
            frames = self.animations[self._anim_name].get("frames",[])
            if frames: self._anim_idx = (self._anim_idx+1) % len(frames)
    def say(self, text, secs=2):
        self._say_text, self._say_until = text, time.time()+float(secs)
    # ── Sensing API ───────────────────────────────────────────────────────
    def touching(self, name):
        t = _find_sprite(name)
        return t is not None and self.rect(_SW,_SH).colliderect(t.rect(_SW,_SH))
    def touching_sprite(self, other, sw, sh):
        return self.rect(sw,sh).colliderect(other.rect(sw,sh))
    def distance_to(self, name):
        t = _find_sprite(name)
        if not t: return 9999
        return math.hypot((self.px-t.px)*_SW, (self.py-t.py)*_SH)
    # ── Clone API ─────────────────────────────────────────────────────────
    def clone(self):
        import copy
        cl = copy.deepcopy(self); cl.px += 0.02; cl.py += 0.02
        cl._clones = []
        self._clones.append(cl)
    def delete_clone(self): pass  # handled by screen

_SW, _SH = 1280, 720

def _find_sprite(name):
    if _ACTIVE_SCREEN:
        for sp in _ACTIVE_SCREEN.sprites:
            if sp.name == name: return sp
    return None
\'\'\'

    # ── CrystalGame ───────────────────────────────────────────────────────

    def _emit_game_class(self):
        return \'\'\'
# ── CrystalGame ───────────────────────────────────────────────────────────────

_ACTIVE_SCREEN = None
_VAR_DISPLAY   = {}

class CrystalGame:
    def __init__(self, screen_map):
        self.screen_map      = screen_map
        self._active_name    = None
        self._overlays       = []
        self._keys_down      = set()
        self._mouse_pos      = (0,0)
        self._mouse_down     = False
        self._timer_start    = time.time()
        self._sounds         = {}
        self._global_vars    = {}
        self._surface        = None
        self._target_fps     = FPS
        self._screen_history = []
        self._draw_queue     = []   # draw calls flushed each render

    def switch_screen(self, name):
        global _ACTIVE_SCREEN
        if name in self.screen_map:
            self._active_name = name
            _ACTIVE_SCREEN    = self.screen_map[name]
            self._screen_history.append(name)
            _ACTIVE_SCREEN.on_load(self)

    def open_overlay(self, name):
        if name in self.screen_map:
            ov = self.screen_map[name]
            if ov not in self._overlays:
                self._overlays.append(ov)
                ov.on_load(self)

    def close_overlay(self):
        if self._overlays: self._overlays.pop()

    def go_back(self):
        if len(self._screen_history) >= 2:
            self._screen_history.pop()
            self.switch_screen(self._screen_history[-1])

    def current_screen_name(self): return self._active_name or ""

    def stop_all(self):
        pygame.event.post(pygame.event.Event(pygame.QUIT))

    def key_down(self, k): return k.lower() in self._keys_down
    def mouse_x(self):     return self._mouse_pos[0]/_SW
    def mouse_y(self):     return self._mouse_pos[1]/_SH
    def mouse_down(self):  return self._mouse_down
    def timer(self):       return time.time()-self._timer_start
    def reset_timer(self): self._timer_start = time.time()
    def get_width(self):   return pygame.display.get_surface().get_width()
    def get_height(self):  return pygame.display.get_surface().get_height()

    def play_sound(self, name):
        snd = self._sounds.get(name)
        if snd: threading.Thread(target=snd.play, daemon=True).start()
    def stop_all_sounds(self): pygame.mixer.stop()
    def set_volume(self,vol):  pygame.mixer.music.set_volume(float(vol)/100)
    def show_var(self,n): _VAR_DISPLAY[n] = True
    def hide_var(self,n): _VAR_DISPLAY[n] = False

    # ── Window ────────────────────────────────────────────────────────────
    def set_title(self,t):   pygame.display.set_caption(str(t))
    def set_fps(self,fps):   self._target_fps = int(fps)
    def screenshot(self,path): pygame.image.save(pygame.display.get_surface(), str(path))
    def set_fullscreen(self, on):
        global _SW, _SH
        surf = pygame.display.set_mode((0,0),pygame.FULLSCREEN) if on \
               else pygame.display.set_mode((_SW,_SH))
        self._surface = surf
    def toggle_fullscreen(self):
        f = pygame.display.get_surface().get_flags()
        self.set_fullscreen(not bool(f & pygame.FULLSCREEN))
    def set_window_size(self,w,h):
        global _SW,_SH; _SW,_SH=int(w),int(h)
        self._surface=pygame.display.set_mode((_SW,_SH))

    # ── Color helper ──────────────────────────────────────────────────────
    def _hex(self,h):
        h=h.lstrip("#")
        return tuple(int(h[i:i+2],16) for i in (0,2,4))

    # ── Event dispatch ────────────────────────────────────────────────────
    def handle_event(self, event):
        global _ACTIVE_SCREEN
        if event.type == pygame.KEYDOWN:
            key = pygame.key.name(event.key)
            self._keys_down.add(key)
            if _ACTIVE_SCREEN:
                _ACTIVE_SCREEN.on_key(self, key)
                _ACTIVE_SCREEN.on_any_key(self, key)
            for ov in self._overlays:
                ov.on_key(self, key); ov.on_any_key(self, key)
        elif event.type == pygame.KEYUP:
            key = pygame.key.name(event.key)
            self._keys_down.discard(key)
            if _ACTIVE_SCREEN: _ACTIVE_SCREEN.on_key_up(self, key)
            for ov in self._overlays: ov.on_key_up(self, key)
        elif event.type == pygame.MOUSEMOTION:
            self._mouse_pos = event.pos
        elif event.type == pygame.MOUSEBUTTONDOWN:
            self._mouse_down = True
            if _ACTIVE_SCREEN: _ACTIVE_SCREEN.on_click(self, event.pos)
            for ov in self._overlays: ov.on_click(self, event.pos)
        elif event.type == pygame.MOUSEBUTTONUP:
            self._mouse_down = False

    def update(self, dt):
        global _ACTIVE_SCREEN
        if _ACTIVE_SCREEN: _ACTIVE_SCREEN.update(self, dt)
        for ov in self._overlays: ov.update(self, dt)

    def queue_draw(self, kind, *args):
        self._draw_queue.append((kind, args))

    def _flush_draw_queue(self, surface):
        sw, sh = surface.get_width(), surface.get_height()
        for kind, args in self._draw_queue:
            if kind == 'text':
                text, x, y, size, color = args
                fnt = pygame.font.SysFont("Segoe UI", max(6, int(size)))
                ts = fnt.render(str(text), True, self._hex(color))
                surface.blit(ts, (int(float(x)*sw), int(float(y)*sh)))
            elif kind == 'rect':
                x, y, w, h, color = args
                pygame.draw.rect(surface, self._hex(color),
                    (int(float(x)*sw), int(float(y)*sh),
                     int(float(w)*sw), int(float(h)*sh)))
            elif kind == 'circle':
                x, y, r, color = args
                pygame.draw.circle(surface, self._hex(color),
                    (int(float(x)*sw), int(float(y)*sh)),
                    max(1, int(float(r)*min(sw,sh))))
            elif kind == 'line':
                x1, y1, x2, y2, color = args
                pygame.draw.line(surface, self._hex(color),
                    (int(float(x1)*sw), int(float(y1)*sh)),
                    (int(float(x2)*sw), int(float(y2)*sh)), 2)
        self._draw_queue.clear()

    def render(self, surface):
        global _ACTIVE_SCREEN
        self._draw_queue = []
        if _ACTIVE_SCREEN: _ACTIVE_SCREEN.render(self, surface)
        for ov in self._overlays: ov.render_sprites_only(self, surface)
        self._flush_draw_queue(surface)
        # Variable overlay
        fnt = pygame.font.SysFont("Consolas", 15)
        y = 8
        for name, shown in _VAR_DISPLAY.items():
            if shown:
                val  = self._global_vars.get(name, "")
                surf = fnt.render(f"{name}: {val}", True, (255,255,255))
                pygame.draw.rect(surface,(0,0,0),(4,y,surf.get_width()+8,surf.get_height()+4))
                surface.blit(surf,(8,y+2)); y += surf.get_height()+6
\'\'\'

    # ── Screen classes ────────────────────────────────────────────────────

    def _emit_screen_classes(self):
        lines = ["# ── Screen classes ──────────────────────────────────────────────────────────", ""]
        for screen in self._project.get("screens", []):
            lines.append(self._emit_one_screen(screen))
        return "\\n".join(lines)

    def _emit_one_screen(self, screen):
        name       = screen["name"]
        cls        = self._safe_class(name)
        bg         = screen.get("bg_color", "#1a1a2e")
        bg_asset   = screen.get("bg_asset") or ""
        sprites    = screen.get("sprites", [])

        def scripts_for(obj, hook):
            return [s for s in obj.get("scripts", []) if s.get("hook") == hook]

        L = []

        # ── class / __init__ ──────────────────────────────────────────
        L += [
            f"class {cls}:",
            f"    BG_COLOR = {bg!r}",
            f"    BG_ASSET = {bg_asset!r}",
            f"    _bg_surf = None",
            f"    def __init__(self):",
        ]
        for sp in sprites:
            sv   = self._safe_var(sp["name"])
            akey = sp.get("asset") or ""
            L += [
                f"        self.{sv} = CrystalSprite(",
                f"            name={sp['name']!r}, asset_key={akey!r},",
                f"            x={sp.get('x',0.5)}, y={sp.get('y',0.5)},",
                f"            scale={sp.get('scale',1.0)}, visible={sp.get('visible',True)},",
                f"            animations={sp.get('animations',{})!r},",
                f"            zorder={sp.get('zorder',0)})",
            ]
        sp_list = ", ".join(f"self.{self._safe_var(s['name'])}" for s in sprites)
        L += [
            f"        self.sprites = [{sp_list}]",
            f"        self._timers = {{}}",
            f"        self._loaded = False",
            f"",
        ]

        # ── on_load ───────────────────────────────────────────────────
        L += [f"    def on_load(self, game):"]
        L += [f"        if self._loaded: return", f"        self._loaded = True"]
        had = False
        for sc in scripts_for(screen, "on_screen_load"):
            for ln in self._blocks(sc, "screen", "        "):
                L.append(ln); had = True
        for sp in sprites:
            sv = self._safe_var(sp["name"])
            for sc in scripts_for(sp, "on_start"):
                for ln in self._blocks(sc, sv, "        "):
                    L.append(ln); had = True
        if not had: L.append("        pass")
        L.append("")

        # ── on_key ────────────────────────────────────────────────────
        L.append(f"    def on_key(self, game, key):")
        had = False
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for sc in scripts_for(src, "on_key"):
                k = sc.get("key","").strip()
                ind = "        "
                if k: L.append(f"        if key == {k!r}:"); ind = "            "
                for ln in self._blocks(sc, owner, ind): L.append(ln)
                had = True
        if not had: L.append("        pass")
        L.append("")

        # ── on_key_up ─────────────────────────────────────────────────
        L.append(f"    def on_key_up(self, game, key):")
        had = False
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for sc in scripts_for(src, "on_key_up"):
                k = sc.get("key","").strip()
                ind = "        "
                if k: L.append(f"        if key == {k!r}:"); ind = "            "
                for ln in self._blocks(sc, owner, ind): L.append(ln)
                had = True
        if not had: L.append("        pass")
        L.append("")

        # ── on_any_key ────────────────────────────────────────────────
        L.append(f"    def on_any_key(self, game, key):")
        had = False
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for sc in scripts_for(src, "on_any_key"):
                for ln in self._blocks(sc, owner, "        "): L.append(ln)
                had = True
        if not had: L.append("        pass")
        L.append("")

        # ── on_click ──────────────────────────────────────────────────
        L.append(f"    def on_click(self, game, pos):")
        had = False
        for sp in sprites:
            sv = self._safe_var(sp["name"])
            scs = scripts_for(sp, "on_click")
            if scs:
                L.append(f"        if self.{sv}.rect(game.get_width(),game.get_height()).collidepoint(pos):")
                for sc in scs:
                    for ln in self._blocks(sc, sv, "            "): L.append(ln)
                had = True
        for sc in scripts_for(screen, "on_click"):
            for ln in self._blocks(sc, "screen", "        "): L.append(ln); had = True
        if not had: L.append("        pass")
        L.append("")

        # ── update ────────────────────────────────────────────────────
        L.append(f"    def update(self, game, dt):")
        L.append(f"        for sp in list(self.sprites): sp.update_animation(dt)")
        # key-hold
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for sc in scripts_for(src, "on_key_hold"):
                k = sc.get("key","").strip()
                ind = "        "
                if k: L.append(f"        if game.key_down({k!r}):"); ind = "            "
                for ln in self._blocks(sc, owner, ind): L.append(ln)
        # timer
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for i, sc in enumerate(scripts_for(src, "on_timer")):
                tk2 = f"_t_{owner}_{i}"
                interval = sc.get("interval","1.0")
                L += [
                    f"        self._timers[{tk2!r}] = self._timers.get({tk2!r},0)+dt",
                    f"        if self._timers[{tk2!r}] >= float({interval!r}):",
                    f"            self._timers[{tk2!r}] = 0",
                ]
                for ln in self._blocks(sc, owner, "            "): L.append(ln)
        # on_update
        for src, owner in [(screen,"screen")]+[(sp,self._safe_var(sp["name"])) for sp in sprites]:
            for sc in scripts_for(src, "on_update"):
                for ln in self._blocks(sc, owner, "        "): L.append(ln)
        # collision
        for sp in sprites:
            sv = self._safe_var(sp["name"])
            for sc in scripts_for(sp, "on_collision"):
                tgt = sc.get("target","").strip()
                tv  = self._safe_var(tgt) if tgt else ""
                if tv and any(s["name"]==tgt for s in sprites):
                    L.append(f"        if self.{sv}.touching_sprite(self.{tv},game.get_width(),game.get_height()):")
                    for ln in self._blocks(sc, sv, "            "): L.append(ln)
        L.append("")

        # ── render ────────────────────────────────────────────────────
        L += [
            f"    def render(self, game, surface):",
            f"        sw, sh = surface.get_width(), surface.get_height()",
            f"        r,g,b  = self._hex_to_rgb(self.BG_COLOR)",
            f"        surface.fill((r,g,b))",
            f"        if self.BG_ASSET:",
            f"            if self.__class__._bg_surf is None:",
            f"                self.__class__._bg_surf = _load_surface(self.BG_ASSET)",
            f"            if self.__class__._bg_surf:",
            f"                surface.blit(pygame.transform.scale(self.__class__._bg_surf,(sw,sh)),(0,0))",
            f"        for sp in sorted(self.sprites,key=lambda s:s.zorder):",
            f"            sp.render(surface,sw,sh)",
            f"",
            f"    def render_sprites_only(self, game, surface):",
            f"        sw,sh=surface.get_width(),surface.get_height()",
            f"        for sp in sorted(self.sprites,key=lambda s:s.zorder):",
            f"            sp.render(surface,sw,sh)",
            f"",
            f"    def set_bg_color(self,c): self.BG_COLOR=c",
            f"",
            f"    def _hex_to_rgb(self,h):",
            f"        h=h.lstrip('#')",
            f"        return tuple(int(h[i:i+2],16) for i in (0,2,4))",
            f"",
        ]
        return "\\n".join(L)

    def _blocks(self, script, owner_var, base_indent):
        """Compile one script's blocks to indented Python lines."""
        sprite_var = "self" if owner_var == "screen" else f"self.{owner_var}"
        screen_var = "self"
        out    = []
        indent = base_indent
        depth_stack = []   # stack of indent levels before each block opener

        for block_inst in script.get("blocks", []):
            bdef = get_block(block_inst.get("id",""))
            if not bdef: continue
            code  = generate_block_code(bdef, block_inst.get("params",{}),
                                         sprite_var=sprite_var,
                                         screen_var=screen_var)
            btype = bdef.get("block_type","")
            if not code.strip(): continue

            for raw in code.split("\\n"):
                if raw.strip():
                    out.append(indent + raw)

            if btype in ("loop","conditional","conditional_else"):
                depth_stack.append(indent)
                indent = indent + "    "
            elif btype == "else_branch":
                # pop back for else:
                if depth_stack:
                    indent = depth_stack[-1]
                out[-1] = indent + "else:"
                indent  = indent + "    "
            else:
                # Heuristic: if we were deeper than base, check if we should dedent
                # (no explicit block_end marker; just stay at current depth)
                pass

        if not out:
            out.append(base_indent + "pass")
        return out

    # ── Entry point ───────────────────────────────────────────────────────

    def _emit_main(self):
        screens  = self._project.get("screens", [])
        first    = screens[0]["name"] if screens else "Main"
        entries  = ", ".join(f"{s['name']!r}:{self._safe_class(s['name'])}()" for s in screens)
        fs       = self._project.get("fullscreen", False)
        adaptive = self._project.get("adaptive", False)

        return f\'\'\'
# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    global _SW, _SH, _ACTIVE_SCREEN
    _ADAPTIVE = {adaptive!r}
    if _ADAPTIVE:
        info = pygame.display.Info()
        _SW, _SH = info.current_w, info.current_h
    else:
        _SW, _SH = WINDOW_W, WINDOW_H

    flags  = pygame.FULLSCREEN if {fs!r} else 0
    if _ADAPTIVE: flags |= pygame.RESIZABLE
    screen = pygame.display.set_mode((_SW,_SH), flags)
    pygame.display.set_caption(WINDOW_TITLE)
    clock  = pygame.time.Clock()

    screen_map = {{{entries}}}
    game       = CrystalGame(screen_map)
    game._surface = screen
    game.switch_screen({first!r})

    running = True
    while running:
        dt = clock.tick(game._target_fps) / 1000.0
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.VIDEORESIZE and _ADAPTIVE:
                _SW,_SH = event.w,event.h
                screen = pygame.display.set_mode((_SW,_SH),flags|pygame.RESIZABLE)
                game._surface = screen
            game.handle_event(event)
        game.update(dt)
        if _ADAPTIVE: _SW,_SH = screen.get_width(),screen.get_height()
        game.render(screen)
        pygame.display.flip()

    pygame.quit()
    sys.exit(0)

if __name__ == "__main__":
    main()
\'\'\'

    def _safe_class(self, name):
        import re
        return "Screen_" + re.sub(r"\\W+","_",name)

    def _safe_var(self, name):
        import re
        return re.sub(r"\\W+","_",name).lower()
