"""Crystal Engine - Block definitions and code generation."""
from engine.constants import CATEGORY_COLORS

BLOCKS = [

    # ── Events ──────────────────────────────────────────────────────────
    {"id": "event_game_start",      "category": "Events",
     "label": "When game starts",   "params": [], "codegen": "", "hook": "on_start"},
    {"id": "event_screen_loaded",   "category": "Events",
     "label": "When screen loaded", "params": [], "codegen": "", "hook": "on_screen_load"},
    {"id": "event_key_pressed",     "category": "Events",
     "label": "When key pressed",   "params": [], "codegen": "", "hook": "on_key"},
    {"id": "event_key_released",    "category": "Events",
     "label": "When key released",  "params": [], "codegen": "", "hook": "on_key_up"},
    {"id": "event_key_held",        "category": "Events",
     "label": "While key held",     "params": [], "codegen": "", "hook": "on_key_hold"},
    {"id": "event_any_key",         "category": "Events",
     "label": "When any key",       "params": [], "codegen": "", "hook": "on_any_key"},
    {"id": "event_sprite_clicked",  "category": "Events",
     "label": "When clicked",       "params": [], "codegen": "", "hook": "on_click"},
    {"id": "event_collision",       "category": "Events",
     "label": "When touching sprite","params": [], "codegen": "", "hook": "on_collision"},
    {"id": "event_timer",           "category": "Events",
     "label": "On timer",           "params": [], "codegen": "", "hook": "on_timer"},
    {"id": "event_update",          "category": "Events",
     "label": "Every frame",        "params": [], "codegen": "", "hook": "on_update"},

    # ── Motion ──────────────────────────────────────────────────────────
    {"id": "motion_move_steps",  "category": "Motion",
     "label": "Move {steps} steps",
     "params": [{"name": "steps", "type": "number", "default": "10"}],
     "codegen": "{__sprite__}.move({steps})"},
    {"id": "motion_set_x",  "category": "Motion",
     "label": "Set x to {x}",
     "params": [{"name": "x", "type": "number", "default": "0.5"}],
     "codegen": "{__sprite__}.set_x({x})"},
    {"id": "motion_set_y",  "category": "Motion",
     "label": "Set y to {y}",
     "params": [{"name": "y", "type": "number", "default": "0.5"}],
     "codegen": "{__sprite__}.set_y({y})"},
    {"id": "motion_change_x",  "category": "Motion",
     "label": "Change x by {dx}",
     "params": [{"name": "dx", "type": "number", "default": "0.01"}],
     "codegen": "{__sprite__}.change_x({dx})"},
    {"id": "motion_change_y",  "category": "Motion",
     "label": "Change y by {dy}",
     "params": [{"name": "dy", "type": "number", "default": "0.01"}],
     "codegen": "{__sprite__}.change_y({dy})"},
    {"id": "motion_goto_xy",  "category": "Motion",
     "label": "Go to x:{x} y:{y}",
     "params": [{"name": "x", "type": "number", "default": "0.5"},
                {"name": "y", "type": "number", "default": "0.5"}],
     "codegen": "{__sprite__}.goto({x}, {y})"},
    {"id": "motion_goto_sprite",  "category": "Motion",
     "label": "Go to {target}",
     "params": [{"name": "target", "type": "sprite", "default": ""}],
     "codegen": "{__sprite__}.goto_sprite('{target}')"},
    {"id": "motion_rotate",  "category": "Motion",
     "label": "Rotate {degrees}°",
     "params": [{"name": "degrees", "type": "number", "default": "15"}],
     "codegen": "{__sprite__}.rotate({degrees})"},
    {"id": "motion_set_angle",  "category": "Motion",
     "label": "Set angle to {angle}°",
     "params": [{"name": "angle", "type": "number", "default": "0"}],
     "codegen": "{__sprite__}.set_angle({angle})"},
    {"id": "motion_bounce_walls",  "category": "Motion",
     "label": "Bounce on edge",
     "params": [], "codegen": "{__sprite__}.bounce_on_edge()"},
    {"id": "motion_set_velocity",  "category": "Motion",
     "label": "Set velocity x:{vx} y:{vy}",
     "params": [{"name": "vx", "type": "number", "default": "0"},
                {"name": "vy", "type": "number", "default": "0"}],
     "codegen": "{__sprite__}.set_velocity({vx}, {vy})"},
    {"id": "motion_apply_velocity",  "category": "Motion",
     "label": "Apply velocity",
     "params": [], "codegen": "{__sprite__}.apply_velocity()"},

    # ── Appearance ──────────────────────────────────────────────────────
    {"id": "appear_show",  "category": "Appearance",
     "label": "Show", "params": [], "codegen": "{__sprite__}.show()"},
    {"id": "appear_hide",  "category": "Appearance",
     "label": "Hide", "params": [], "codegen": "{__sprite__}.hide()"},
    {"id": "appear_set_scale",  "category": "Appearance",
     "label": "Set scale to {scale}",
     "params": [{"name": "scale", "type": "number", "default": "1.0"}],
     "codegen": "{__sprite__}.set_scale({scale})"},
    {"id": "appear_change_scale",  "category": "Appearance",
     "label": "Change scale by {delta}",
     "params": [{"name": "delta", "type": "number", "default": "0.1"}],
     "codegen": "{__sprite__}.change_scale({delta})"},
    {"id": "appear_set_opacity",  "category": "Appearance",
     "label": "Set opacity {alpha}%",
     "params": [{"name": "alpha", "type": "number", "default": "100"}],
     "codegen": "{__sprite__}.set_opacity({alpha})"},
    {"id": "appear_set_tint",  "category": "Appearance",
     "label": "Set tint {color}",
     "params": [{"name": "color", "type": "color", "default": "#ffffff"}],
     "codegen": "{__sprite__}.set_tint('{color}')"},
    {"id": "appear_clear_tint",  "category": "Appearance",
     "label": "Clear tint", "params": [],
     "codegen": "{__sprite__}.clear_tint()"},
    {"id": "appear_play_animation",  "category": "Appearance",
     "label": "Play animation {anim}",
     "params": [{"name": "anim", "type": "string", "default": "idle"}],
     "codegen": "{__sprite__}.play_animation('{anim}')"},
    {"id": "appear_stop_animation",  "category": "Appearance",
     "label": "Stop animation",
     "params": [], "codegen": "{__sprite__}.stop_animation()"},
    {"id": "appear_say",  "category": "Appearance",
     "label": "Say {text} for {secs}s",
     "params": [{"name": "text", "type": "string", "default": "Hello!"},
                {"name": "secs", "type": "number", "default": "2"}],
     "codegen": "{__sprite__}.say('{text}', {secs})"},
    {"id": "appear_set_layer",  "category": "Appearance",
     "label": "Set layer to {z}",
     "params": [{"name": "z", "type": "number", "default": "0"}],
     "codegen": "{__sprite__}.set_layer({z})"},

    # ── Screen ──────────────────────────────────────────────────────────
    {"id": "screen_set_bg_color",  "category": "Screen",
     "label": "Set background color {color}",
     "params": [{"name": "color", "type": "color", "default": "#1a1a2e"}],
     "codegen": "{__screen__}.set_bg_color('{color}')"},
    {"id": "screen_switch",  "category": "Screen",
     "label": "Switch to screen {screen}",
     "params": [{"name": "screen", "type": "screen", "default": ""}],
     "codegen": "game.switch_screen('{screen}')"},
    {"id": "screen_open_overlay",  "category": "Screen",
     "label": "Open overlay {screen}",
     "params": [{"name": "screen", "type": "screen", "default": ""}],
     "codegen": "game.open_overlay('{screen}')"},
    {"id": "screen_close_overlay",  "category": "Screen",
     "label": "Close overlay",
     "params": [], "codegen": "game.close_overlay()"},
    {"id": "screen_go_back",  "category": "Screen",
     "label": "Go back",
     "params": [], "codegen": "game.go_back()"},
    {"id": "screen_get_name",  "category": "Screen",
     "label": "Current screen name → {var}",
     "params": [{"name": "var", "type": "var", "default": "screen_name"}],
     "codegen": "{var} = game.current_screen_name()"},

    # ── Control ─────────────────────────────────────────────────────────
    {"id": "control_wait",  "category": "Control",
     "label": "Wait {secs} seconds",
     "params": [{"name": "secs", "type": "number", "default": "1"}],
     "codegen": "yield ('wait', {secs})"},
    {"id": "control_repeat",  "category": "Control",
     "label": "Repeat {times} times",
     "params": [{"name": "times", "type": "number", "default": "10"}],
     "codegen": "for _i in range(int({times})):", "block_type": "loop"},
    {"id": "control_forever",  "category": "Control",
     "label": "Forever",
     "params": [], "codegen": "while True:", "block_type": "loop"},
    {"id": "control_if",  "category": "Control",
     "label": "If {condition}",
     "params": [{"name": "condition", "type": "expr", "default": "True"}],
     "codegen": "if {condition}:", "block_type": "conditional"},
    {"id": "control_if_else",  "category": "Control",
     "label": "If {condition} / else",
     "params": [{"name": "condition", "type": "expr", "default": "True"}],
     "codegen": "if {condition}:", "block_type": "conditional_else"},
    {"id": "control_else",  "category": "Control",
     "label": "Else",
     "params": [], "codegen": "else:", "block_type": "else_branch"},
    {"id": "control_stop_this",  "category": "Control",
     "label": "Stop this script",
     "params": [], "codegen": "return"},
    {"id": "control_stop_all",  "category": "Control",
     "label": "Stop all scripts",
     "params": [], "codegen": "game.stop_all()"},
    {"id": "control_clone",  "category": "Control",
     "label": "Clone this sprite",
     "params": [], "codegen": "{__sprite__}.clone()"},
    {"id": "control_delete_clone",  "category": "Control",
     "label": "Delete this clone",
     "params": [], "codegen": "{__sprite__}.delete_clone()"},
    {"id": "control_break",  "category": "Control",
     "label": "Break out of loop",
     "params": [], "codegen": "break"},
    {"id": "control_continue",  "category": "Control",
     "label": "Continue loop",
     "params": [], "codegen": "continue"},

    # ── Variables ────────────────────────────────────────────────────────
    {"id": "var_set",  "category": "Variables",
     "label": "Set {var} = {value}",
     "params": [{"name": "var",   "type": "var",  "default": "score"},
                {"name": "value", "type": "expr", "default": "0"}],
     "codegen": "{var} = {value}"},
    {"id": "var_change",  "category": "Variables",
     "label": "Change {var} by {amount}",
     "params": [{"name": "var",    "type": "var",    "default": "score"},
                {"name": "amount", "type": "number",  "default": "1"}],
     "codegen": "{var} += {amount}"},
    {"id": "var_show",  "category": "Variables",
     "label": "Show {var} on screen",
     "params": [{"name": "var", "type": "var", "default": "score"}],
     "codegen": "game.show_var('{var}')"},
    {"id": "var_hide",  "category": "Variables",
     "label": "Hide {var}",
     "params": [{"name": "var", "type": "var", "default": "score"}],
     "codegen": "game.hide_var('{var}')"},

    # ── Lists ────────────────────────────────────────────────────────────
    {"id": "list_create",  "category": "Lists",
     "label": "Create list {var}",
     "params": [{"name": "var", "type": "var", "default": "my_list"}],
     "codegen": "{var} = []"},
    {"id": "list_append",  "category": "Lists",
     "label": "Add {item} to {var}",
     "params": [{"name": "item", "type": "expr", "default": "0"},
                {"name": "var",  "type": "var",  "default": "my_list"}],
     "codegen": "{var}.append({item})"},
    {"id": "list_delete",  "category": "Lists",
     "label": "Delete item {idx} from {var}",
     "params": [{"name": "idx", "type": "number", "default": "0"},
                {"name": "var", "type": "var",    "default": "my_list"}],
     "codegen": "del {var}[int({idx})]"},
    {"id": "list_get",  "category": "Lists",
     "label": "Get {var}[{idx}] → {out}",
     "params": [{"name": "var", "type": "var",    "default": "my_list"},
                {"name": "idx", "type": "number",  "default": "0"},
                {"name": "out", "type": "var",     "default": "item"}],
     "codegen": "{out} = {var}[int({idx})]"},
    {"id": "list_length",  "category": "Lists",
     "label": "Length of {var} → {out}",
     "params": [{"name": "var", "type": "var", "default": "my_list"},
                {"name": "out", "type": "var", "default": "length"}],
     "codegen": "{out} = len({var})"},
    {"id": "list_contains",  "category": "Lists",
     "label": "{var} contains {item}?",
     "params": [{"name": "var",  "type": "var",  "default": "my_list"},
                {"name": "item", "type": "expr", "default": "0"}],
     "codegen": "({item} in {var})"},

    # ── Operators ────────────────────────────────────────────────────────
    {"id": "op_random",  "category": "Operators",
     "label": "Random {min} to {max}",
     "params": [{"name": "min", "type": "number", "default": "1"},
                {"name": "max", "type": "number", "default": "10"}],
     "codegen": "random.randint(int({min}), int({max}))"},
    {"id": "op_random_float",  "category": "Operators",
     "label": "Random float {min}–{max}",
     "params": [{"name": "min", "type": "number", "default": "0.0"},
                {"name": "max", "type": "number", "default": "1.0"}],
     "codegen": "random.uniform({min}, {max})"},
    {"id": "op_round",  "category": "Operators",
     "label": "Round {val}",
     "params": [{"name": "val", "type": "expr", "default": "0"}],
     "codegen": "round({val})"},
    {"id": "op_abs",  "category": "Operators",
     "label": "Abs {val}",
     "params": [{"name": "val", "type": "expr", "default": "0"}],
     "codegen": "abs({val})"},
    {"id": "op_floor",  "category": "Operators",
     "label": "Floor {val}",
     "params": [{"name": "val", "type": "expr", "default": "0"}],
     "codegen": "math.floor({val})"},
    {"id": "op_ceil",  "category": "Operators",
     "label": "Ceil {val}",
     "params": [{"name": "val", "type": "expr", "default": "0"}],
     "codegen": "math.ceil({val})"},
    {"id": "op_sqrt",  "category": "Operators",
     "label": "Sqrt {val}",
     "params": [{"name": "val", "type": "expr", "default": "0"}],
     "codegen": "math.sqrt({val})"},
    {"id": "op_sin",  "category": "Operators",
     "label": "Sin {deg}°",
     "params": [{"name": "deg", "type": "expr", "default": "0"}],
     "codegen": "math.sin(math.radians({deg}))"},
    {"id": "op_cos",  "category": "Operators",
     "label": "Cos {deg}°",
     "params": [{"name": "deg", "type": "expr", "default": "0"}],
     "codegen": "math.cos(math.radians({deg}))"},
    {"id": "op_clamp",  "category": "Operators",
     "label": "Clamp {val} between {lo} and {hi}",
     "params": [{"name": "val", "type": "expr",   "default": "0"},
                {"name": "lo",  "type": "number",  "default": "0"},
                {"name": "hi",  "type": "number",  "default": "1"}],
     "codegen": "max({lo}, min({hi}, {val}))"},
    {"id": "op_lerp",  "category": "Operators",
     "label": "Lerp {a} → {b} by {t}",
     "params": [{"name": "a", "type": "expr",   "default": "0"},
                {"name": "b", "type": "expr",   "default": "1"},
                {"name": "t", "type": "number", "default": "0.1"}],
     "codegen": "({a} + ({b} - {a}) * {t})"},
    {"id": "op_str_join",  "category": "Operators",
     "label": "Join {a} and {b} → {out}",
     "params": [{"name": "a",   "type": "expr", "default": "''"},
                {"name": "b",   "type": "expr", "default": "''"},
                {"name": "out", "type": "var",  "default": "result"}],
     "codegen": "{out} = str({a}) + str({b})"},
    {"id": "op_str_split",  "category": "Operators",
     "label": "Split {text} by {sep} → {out}",
     "params": [{"name": "text", "type": "expr",   "default": "''"},
                {"name": "sep",  "type": "string",  "default": ","},
                {"name": "out",  "type": "var",     "default": "parts"}],
     "codegen": "{out} = str({text}).split('{sep}')"},
    {"id": "op_str_format",  "category": "Operators",
     "label": "Format '{fmt}' → {out}",
     "params": [{"name": "fmt", "type": "string", "default": "Score: {score}"},
                {"name": "out", "type": "var",    "default": "text"}],
     "codegen": "{out} = f'{{{fmt}}}'"},
    {"id": "op_int",  "category": "Operators",
     "label": "Int of {val} → {out}",
     "params": [{"name": "val", "type": "expr", "default": "0"},
                {"name": "out", "type": "var",  "default": "n"}],
     "codegen": "{out} = int({val})"},
    {"id": "op_float",  "category": "Operators",
     "label": "Float of {val} → {out}",
     "params": [{"name": "val", "type": "expr", "default": "0"},
                {"name": "out", "type": "var",  "default": "n"}],
     "codegen": "{out} = float({val})"},
    {"id": "op_str",  "category": "Operators",
     "label": "String of {val} → {out}",
     "params": [{"name": "val", "type": "expr", "default": "0"},
                {"name": "out", "type": "var",  "default": "s"}],
     "codegen": "{out} = str({val})"},

    # ── Sensing ──────────────────────────────────────────────────────────
    {"id": "sense_key_down",  "category": "Sensing",
     "label": "Key {key} is down?",
     "params": [{"name": "key", "type": "string", "default": "space"}],
     "codegen": "game.key_down('{key}')"},
    {"id": "sense_mouse_x",  "category": "Sensing",
     "label": "Mouse x → {out}",
     "params": [{"name": "out", "type": "var", "default": "mx"}],
     "codegen": "{out} = game.mouse_x()"},
    {"id": "sense_mouse_y",  "category": "Sensing",
     "label": "Mouse y → {out}",
     "params": [{"name": "out", "type": "var", "default": "my"}],
     "codegen": "{out} = game.mouse_y()"},
    {"id": "sense_mouse_down",  "category": "Sensing",
     "label": "Mouse button down?",
     "params": [], "codegen": "game.mouse_down()"},
    {"id": "sense_touching",  "category": "Sensing",
     "label": "Touching {target}?",
     "params": [{"name": "target", "type": "sprite", "default": ""}],
     "codegen": "{__sprite__}.touching('{target}')"},
    {"id": "sense_distance",  "category": "Sensing",
     "label": "Distance to {target} → {out}",
     "params": [{"name": "target", "type": "sprite", "default": ""},
                {"name": "out",    "type": "var",    "default": "dist"}],
     "codegen": "{out} = {__sprite__}.distance_to('{target}')"},
    {"id": "sense_timer",  "category": "Sensing",
     "label": "Timer → {out}",
     "params": [{"name": "out", "type": "var", "default": "t"}],
     "codegen": "{out} = game.timer()"},
    {"id": "sense_reset_timer",  "category": "Sensing",
     "label": "Reset timer",
     "params": [], "codegen": "game.reset_timer()"},
    {"id": "sense_sprite_x",  "category": "Sensing",
     "label": "{sprite} x → {out}",
     "params": [{"name": "sprite", "type": "sprite", "default": ""},
                {"name": "out",    "type": "var",    "default": "px"}],
     "codegen": "{out} = {__screen__}.{sprite}.px if hasattr({__screen__}, '{sprite}') else 0"},
    {"id": "sense_sprite_y",  "category": "Sensing",
     "label": "{sprite} y → {out}",
     "params": [{"name": "sprite", "type": "sprite", "default": ""},
                {"name": "out",    "type": "var",    "default": "py"}],
     "codegen": "{out} = {__screen__}.{sprite}.py if hasattr({__screen__}, '{sprite}') else 0"},

    # ── Drawing ──────────────────────────────────────────────────────────
    {"id": "draw_text",  "category": "Drawing",
     "label": "Draw text {text} at {x},{y} size {size} color {color}",
     "params": [{"name": "text",  "type": "expr",   "default": "'Hello'"},
                {"name": "x",     "type": "number",  "default": "0.5"},
                {"name": "y",     "type": "number",  "default": "0.5"},
                {"name": "size",  "type": "number",  "default": "24"},
                {"name": "color", "type": "color",   "default": "#ffffff"}],
     "codegen": "game.draw_text(surface, {text}, {x}, {y}, int({size}), '{color}')"},
    {"id": "draw_rect",  "category": "Drawing",
     "label": "Draw rect x:{x} y:{y} w:{w} h:{h} color {color}",
     "params": [{"name": "x",     "type": "number", "default": "0.1"},
                {"name": "y",     "type": "number", "default": "0.1"},
                {"name": "w",     "type": "number", "default": "0.2"},
                {"name": "h",     "type": "number", "default": "0.1"},
                {"name": "color", "type": "color",  "default": "#ffffff"}],
     "codegen": "game.draw_rect(surface, {x}, {y}, {w}, {h}, '{color}')"},
    {"id": "draw_circle",  "category": "Drawing",
     "label": "Draw circle x:{x} y:{y} r:{r} color {color}",
     "params": [{"name": "x",     "type": "number", "default": "0.5"},
                {"name": "y",     "type": "number", "default": "0.5"},
                {"name": "r",     "type": "number", "default": "0.05"},
                {"name": "color", "type": "color",  "default": "#ff0000"}],
     "codegen": "game.draw_circle(surface, {x}, {y}, {r}, '{color}')"},
    {"id": "draw_line",  "category": "Drawing",
     "label": "Draw line ({x1},{y1}) → ({x2},{y2}) color {color}",
     "params": [{"name": "x1",    "type": "number", "default": "0.1"},
                {"name": "y1",    "type": "number", "default": "0.1"},
                {"name": "x2",    "type": "number", "default": "0.9"},
                {"name": "y2",    "type": "number", "default": "0.9"},
                {"name": "color", "type": "color",  "default": "#ffffff"}],
     "codegen": "game.draw_line(surface, {x1}, {y1}, {x2}, {y2}, '{color}')"},

    # ── Sound ────────────────────────────────────────────────────────────
    {"id": "sound_play",  "category": "Sound",
     "label": "Play sound {sound}",
     "params": [{"name": "sound", "type": "string", "default": "beep"}],
     "codegen": "game.play_sound('{sound}')"},
    {"id": "sound_stop_all",  "category": "Sound",
     "label": "Stop all sounds",
     "params": [], "codegen": "game.stop_all_sounds()"},
    {"id": "sound_set_volume",  "category": "Sound",
     "label": "Set volume {vol}%",
     "params": [{"name": "vol", "type": "number", "default": "100"}],
     "codegen": "game.set_volume({vol})"},

    # ── Window ───────────────────────────────────────────────────────────
    {"id": "window_set_title",  "category": "Window",
     "label": "Set title {title}",
     "params": [{"name": "title", "type": "string", "default": "My Game"}],
     "codegen": "game.set_title('{title}')"},
    {"id": "window_toggle_fullscreen",  "category": "Window",
     "label": "Toggle fullscreen",
     "params": [], "codegen": "game.toggle_fullscreen()"},
    {"id": "window_set_fullscreen",  "category": "Window",
     "label": "Set fullscreen {on}",
     "params": [{"name": "on", "type": "string", "default": "True"}],
     "codegen": "game.set_fullscreen({on} in ('True', True, 1))"},
    {"id": "window_set_size",  "category": "Window",
     "label": "Set window size {w}×{h}",
     "params": [{"name": "w", "type": "number", "default": "1280"},
                {"name": "h", "type": "number", "default": "720"}],
     "codegen": "game.set_window_size(int({w}), int({h}))"},
    {"id": "window_set_fps",  "category": "Window",
     "label": "Set FPS {fps}",
     "params": [{"name": "fps", "type": "number", "default": "60"}],
     "codegen": "game.set_fps(int({fps}))"},
    {"id": "window_screenshot",  "category": "Window",
     "label": "Save screenshot {path}",
     "params": [{"name": "path", "type": "string", "default": "shot.png"}],
     "codegen": "game.screenshot('{path}')"},

    # ── Debug ────────────────────────────────────────────────────────────
    {"id": "debug_print",  "category": "Debug",
     "label": "Print {msg}",
     "params": [{"name": "msg", "type": "expr", "default": "'hello'"}],
     "codegen": "print({msg})"},
    {"id": "debug_print_var",  "category": "Debug",
     "label": "Print {label}: {val}",
     "params": [{"name": "label", "type": "string", "default": "score"},
                {"name": "val",   "type": "expr",   "default": "score"}],
     "codegen": "print(f'{label}: {{str({val})}}')" },
    {"id": "debug_assert",  "category": "Debug",
     "label": "Assert {cond} or raise {msg}",
     "params": [{"name": "cond", "type": "expr",   "default": "True"},
                {"name": "msg",  "type": "string",  "default": "assertion failed"}],
     "codegen": "assert {cond}, '{msg}'"},

    # ── Network ──────────────────────────────────────────────────────────
    {"id": "net_http_get",  "category": "Network",
     "label": "HTTP GET {url} → {var}",
     "params": [{"name": "url", "type": "string", "default": "https://example.com"},
                {"name": "var", "type": "var",    "default": "response"}],
     "codegen": ("import urllib.request as _ur\n"
                 "try:\n"
                 "    with _ur.urlopen('{url}') as _r: {var} = _r.read().decode()\n"
                 "except Exception as _e: {var} = str(_e)")},

    # ── Python ───────────────────────────────────────────────────────────
    {"id": "python_raw",  "category": "Python",
     "label": "Python code",
     "params": [{"name": "code", "type": "string",
                 "default": "pass"}],
     "codegen": "{code}", "multiline": True},
]

# Lookup tables
BLOCK_BY_ID       = {b["id"]: b for b in BLOCKS}
BLOCKS_BY_CATEGORY = {}
for b in BLOCKS:
    BLOCKS_BY_CATEGORY.setdefault(b["category"], []).append(b)


def get_block(block_id):
    return BLOCK_BY_ID.get(block_id)


def render_block_label(block, params):
    lbl = block["label"]
    for p in block.get("params", []):
        n = p["name"]
        lbl = lbl.replace(f"{{{n}}}", str(params.get(n, p.get("default", ""))))
    return lbl


def generate_block_code(block, params, sprite_var="sprite", screen_var="screen"):
    tmpl = block.get("codegen", "")
    result = tmpl.replace("{__sprite__}", sprite_var).replace("{__screen__}", screen_var)
    for p in block.get("params", []):
        n = p["name"]
        result = result.replace(f"{{{n}}}", str(params.get(n, p.get("default", ""))))
    return result
